language: ruby
rvm:
- 2.4

install:
  - gem install jekyll html-proofer
  - bundle install

before_script: bundle exec jekyll build

script: htmlproofer ./_site --allow-hash-href --disable-external --assume-extension

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false
