# Site settings
title: Governing Documents Template
organization: Triangle Fraternity
description: > # this means to ignore newlines until "timezone:"
  Template for all governing documents of Triangle Fraternity at Michigan Technological University
timezone: America/Detroit

# Build settings
markdown: kramdown

collections:
  appendicies:
    output: true
    permalink: /appendicies/:title

defaults:
  - scope:
      type: "appendicies"
    values:
      layout: "appendix"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - docker-compose.yml
  - README.md
  - .travis.yml
  - .gitignore
  - LICENSE
